"""tambah media konten situs dan deskripsi gambar produk

Revision ID: 93c23db01dd4
Revises: 088f402eae9a
Create Date: 2026-10-01 14:44:52.619615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c23db01dd4'
down_revision: Union[str, Sequence[str], None] = '088f402eae9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_file', sa.String(length=100), nullable=False),
    sa.Column('nama_asli', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=50), nullable=False),
    sa.Column('ukuran_byte', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_file')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_table('konten_situs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('halaman', sa.String(length=30), nullable=False),
    sa.Column('bagian', sa.String(length=50), nullable=False),
    sa.Column('urutan', sa.Integer(), server_default='0', nullable=False),
    sa.Column('judul', sa.String(length=150), nullable=True),
    sa.Column('subjudul', sa.String(length=150), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('gambar_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['gambar_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_konten_situs_halaman_bagian', 'konten_situs', ['halaman', 'bagian'], unique=False)
    op.create_index(op.f('ix_konten_situs_id'), 'konten_situs', ['id'], unique=False)
    op.add_column('produk', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.add_column('produk', sa.Column('gambar_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_produk_gambar_id_media', 'produk', 'media', ['gambar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_produk_gambar_id_media', 'produk', type_='foreignkey')
    op.drop_column('produk', 'gambar_id')
    op.drop_column('produk', 'deskripsi')
    op.drop_index(op.f('ix_konten_situs_id'), table_name='konten_situs')
    op.drop_index('ix_konten_situs_halaman_bagian', table_name='konten_situs')
    op.drop_table('konten_situs')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
